// 语言表：Google/通用 BCP-47 代码 <-> 中文名/英文名
// 用于 Google Web（自动检测源语言，targetLang 直接用下面的 code）
// DeepL / OpenAI 兼容后端各自负责把中文名映射或直接复用 code

export const DEFAULT_TARGET = "zh-CN";

// code: [中文名, English name]
export const LANGS = {
  "auto": ["自动检测", "Detect"],
  "af": ["南非荷兰语", "Afrikaans"],
  "sq": ["阿尔巴尼亚语", "Albanian"],
  "am": ["阿姆哈拉语", "Amharic"],
  "ar": ["阿拉伯语", "Arabic"],
  "hy": ["亚美尼亚语", "Armenian"],
  "az": ["阿塞拜疆语", "Azerbaijani"],
  "eu": ["巴斯克语", "Basque"],
  "be": ["白俄罗斯语", "Belarusian"],
  "bn": ["孟加拉语", "Bengali"],
  "bs": ["波斯尼亚语", "Bosnian"],
  "bg": ["保加利亚语", "Bulgarian"],
  "ca": ["加泰罗尼亚语", "Catalan"],
  "ceb": ["宿务语", "Cebuano"],
  "zh-CN": ["中文（简体）", "Chinese (Simplified)"],
  "zh-TW": ["中文（繁體）", "Chinese (Traditional)"],
  "co": ["科西嘉语", "Corsican"],
  "hr": ["克罗地亚语", "Croatian"],
  "cs": ["捷克语", "Czech"],
  "da": ["丹麦语", "Danish"],
  "nl": ["荷兰语", "Dutch"],
  "en": ["英语", "English"],
  "eo": ["世界语", "Esperanto"],
  "et": ["爱沙尼亚语", "Estonian"],
  "fi": ["芬兰语", "Finnish"],
  "fr": ["法语", "French"],
  "gl": ["加利西亚语", "Galician"],
  "ka": ["格鲁吉亚语", "Georgian"],
  "de": ["德语", "German"],
  "el": ["希腊语", "Greek"],
  "gu": ["古吉拉特语", "Gujarati"],
  "ht": ["海地克里奥尔语", "Haitian Creole"],
  "ha": ["豪萨语", "Hausa"],
  "haw": ["夏威夷语", "Hawaiian"],
  "he": ["希伯来语", "Hebrew"],
  "hi": ["印地语", "Hindi"],
  "hmn": ["苗语", "Hmong"],
  "hu": ["匈牙利语", "Hungarian"],
  "is": ["冰岛语", "Icelandic"],
  "ig": ["伊博语", "Igbo"],
  "id": ["印度尼西亚语", "Indonesian"],
  "ga": ["爱尔兰语", "Irish"],
  "it": ["意大利语", "Italian"],
  "ja": ["日语", "Japanese"],
  "jv": ["爪哇语", "Javanese"],
  "kn": ["卡纳达语", "Kannada"],
  "kk": ["哈萨克语", "Kazakh"],
  "km": ["高棉语", "Khmer"],
  "ko": ["韩语", "Korean"],
  "ku": ["库尔德语", "Kurdish"],
  "ky": ["吉尔吉斯语", "Kyrgyz"],
  "lo": ["老挝语", "Lao"],
  "la": ["拉丁语", "Latin"],
  "lv": ["拉脱维亚语", "Latvian"],
  "lt": ["立陶宛语", "Lithuanian"],
  "lb": ["卢森堡语", "Luxembourgish"],
  "mk": ["马其顿语", "Macedonian"],
  "mg": ["马达加斯加语", "Malagasy"],
  "ms": ["马来语", "Malay"],
  "ml": ["马拉雅拉姆语", "Malayalam"],
  "mt": ["马耳他语", "Maltese"],
  "mi": ["毛利语", "Maori"],
  "mr": ["马拉地语", "Marathi"],
  "mn": ["蒙古语", "Mongolian"],
  "my": ["缅甸语", "Myanmar (Burmese)"],
  "ne": ["尼泊尔语", "Nepali"],
  "no": ["挪威语", "Norwegian"],
  "ny": ["齐切瓦语", "Chichewa"],
  "or": ["奥里亚语", "Odia (Oriya)"],
  "ps": ["普什图语", "Pashto"],
  "fa": ["波斯语", "Persian"],
  "pl": ["波兰语", "Polish"],
  "pt": ["葡萄牙语", "Portuguese"],
  "pa": ["旁遮普语", "Punjabi"],
  "ro": ["罗马尼亚语", "Romanian"],
  "ru": ["俄语", "Russian"],
  "sm": ["萨摩亚语", "Samoan"],
  "gd": ["苏格兰盖尔语", "Scots Gaelic"],
  "sr": ["塞尔维亚语", "Serbian"],
  "st": ["塞索托语", "Sesotho"],
  "sn": ["绍纳语", "Shona"],
  "sd": ["信德语", "Sindhi"],
  "si": ["僧伽罗语", "Sinhala"],
  "sk": ["斯洛伐克语", "Slovak"],
  "sl": ["斯洛文尼亚语", "Slovenian"],
  "so": ["索马里语", "Somali"],
  "es": ["西班牙语", "Spanish"],
  "su": ["巽他语", "Sundanese"],
  "sw": ["斯瓦希里语", "Swahili"],
  "sv": ["瑞典语", "Swedish"],
  "tl": ["菲律宾语", "Filipino"],
  "tg": ["塔吉克语", "Tajik"],
  "ta": ["泰米尔语", "Tamil"],
  "tt": ["鞑靼语", "Tatar"],
  "te": ["泰卢固语", "Telugu"],
  "th": ["泰语", "Thai"],
  "tr": ["土耳其语", "Turkish"],
  "tk": ["土库曼语", "Turkmen"],
  "uk": ["乌克兰语", "Ukrainian"],
  "ur": ["乌尔都语", "Urdu"],
  "ug": ["维吾尔语", "Uyghur"],
  "uz": ["乌兹别克语", "Uzbek"],
  "vi": ["越南语", "Vietnamese"],
  "cy": ["威尔士语", "Welsh"],
  "xh": ["科萨语", "Xhosa"],
  "yi": ["意第绪语", "Yiddish"],
  "yo": ["约鲁巴语", "Yoruba"],
  "zu": ["祖鲁语", "Zulu"]
};

// 排序：中文名，auto 放最后
export function sortedLangEntries() {
  return Object.entries(LANGS).sort((a, b) => {
    if (a[0] === "auto") return 1;
    if (b[0] === "auto") return -1;
    return a[1][0].localeCompare(b[1][0], "zh");
  });
}

export function langName(code, fb = code) {
  return (LANGS[code] && LANGS[code][0]) || fb;
}
